dist: xenial
language: python
sudo: false

python:
  - 3.6
  - 3.7

install:
  - pip install -U pip setuptools pipenv
  - pipenv install -d --system
  - pip install codecov

script: pytest

after_success:
  - codecov

before_deploy:
  - make clear
  - make apiset/version.py
  - make swagger_ui

deploy:
  provider: pypi
  user: yttrium
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: aioworkers/apiset
    condition: $TRAVIS_PYTHON_VERSION = 3.6
  skip_cleanup: true
  password:
    secure: brDdxNgS8SufoQaY94IsHEKR9ujiDj3zRIEM1BJvlqhnRmI+3WtOgbg9dL/ESuyo9O5N67vsKNxId3s1SOAjzdtF2IrHXl2Zg9Nphzy6dJS22BaLKvDQpbPWRkP282AeBn/wAlpU7GitF2x14zN93a0VciHbtiWTTfzkkP4JMnyput9Vp3RcmhJyuPB48ZrSyCEEU4SbPSuY9XzNAcgQ5mI9fCjk00b+OG8WiApAkA2FjEEFGr+UqKX0c2dKAJ7utYc3xq9lIjUoJ+aKcu4QR0xDFNRfJt1dL5vJYDifJ+4z3zPmzaxVBx/SIg5RnRw8DGeE4iPQNNLMXTZkNg+9e9kXLm5LHexGXrWGuG/c+88NQ7h2nACdQekE2/sOLTkXWzQmXlKBUvndZ5fNgWrXJti+zhWrf0tTmwwIBV01zLPqztLS9UkCprhyt9wXiqZH6Z6hYfdpxsbrCIgXRDLver2JW+QZi8xzO0mWjAFVHJu81Ks8nfOx92Z4YzTnxF3GBTUacfYH9zTkckwJmTHVN3ul2IlPmed4ih3RILXbUo0D2dpPXdblvcqEJe8wQsGLDab3vwj8P2CHhK4gxzPykXcPSY7zf99kCIT4Mk4r+mFUifJEbJ+EfVxicJ5//sO8hCQEwhJ1BLf5jGyqhWolZbMWjfiz4t4bd06n/mktTlg=
